spring.application.name=project-hk-backend
spring.datasource.url=jdbc:postgresql://ep-sparkling-dust-anigg66g-pooler.c-6.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_3pzDs0OocMYg&sslmode=require&channelBinding=require
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

google.client-id=38505021736-fj2gnk432c5n00gcku1nl419g1jktcno.apps.googleusercontent.com
google.client-secret=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

igbd.client-id=djwfo4a8krj1uf92ryfi2tsb0w76ie
igdb.client-secret=jzhx6l4dkzdegr7lf0sxw17br47soo

app.jwt.secret=E(Fg6BYs](Hc(eFbWt:[34iUJO*3n(wJ0G[n%=Q/Xpa
app.jwt.expiry=3600
app.jwt.refresh-expiry=2592000